### PR TITLE
Fix/otrs us agreement

### PR DESCRIPTION
**Pull request by varun257**
change text for us customers

resolves MBE-375

### CODE REVIEW

**Comment by varun257** [comment]
"Translation is required for this"

**Comment by marie-j** [comment]
@varun257 Could you rebase on `v7.x.x` branch ?
Thanks

**Comment by varun257** [comment]
> @varun257 Could you rebase on `v7.x.x` branch ?
> Thanks

@marie-j  Have rebased and i still see some code attached

**Comment by antleblanc** [comment]
@varun257 I've done the rebase on top of `v7.x.x` branch.

Hope it's help you.

Thank!s

**Pull request merged**
